---
- name: MMS | Check if my_package is installed
  command: dpkg-query -W mongodb-mms-backup-agent
  register: agent_check_deb
  become: yes
  failed_when: agent_check_deb.rc > 1
  changed_when: agent_check_deb.rc == 1
  tags:
    -mms


- name: MMS | download package
  get_url:
    url="https://cloud.mongodb.com/download/agent/backup/mongodb-mms-backup-agent_4.4.1.402-1_amd64.deb"
    dest="/tmp/mongodb-mms-backup-agent_4.4.1.402-1_amd64.deb"
  when: agent_check_deb.rc == 1
  tags:
    -mms

- name: MMS | install package
  apt: deb="/tmp/mongodb-mms-backup-agent_4.4.1.402-1_amd64.deb"
  become: true
  when: agent_check_deb.rc == 1
  tags:
    -mms

- name: MMS | API Key
  lineinfile: dest=/etc/mongodb-mms/backup-agent.config regexp='^mmsApiKey=' line='mmsApiKey={{ mmsApiKey | mandatory }}'
  become: true
  tags:
    -mms


- name: MMS | Start agent
  shell: start mongodb-mms-backup-agent
  become: true
  tags:
    -mms

